# Generated by Django 4.1.13 on 2024-03-30 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("file", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
