# Generated by Django 5.0.3 on 2024-04-23 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='file_type',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
