# Generated by Django 4.1.13 on 2024-03-30 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("verified", models.BooleanField(default=False)),
                ("active", models.BooleanField(default=True)),
                ("firstName", models.CharField(max_length=20)),
                ("lastName", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=254)),
                ("password", models.CharField(max_length=20)),
                (
                    "picture",
                    models.ImageField(
                        blank=True, upload_to="profile_pictures/%y/%m/%d/"
                    ),
                ),
            ],
            options={
                "db_table": "user",
            },
        ),
    ]
