# Generated by Django 5.0.3 on 2024-04-03 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filehive_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='full_name',
        ),
    ]
