# Generated by Django 5.0.3 on 2024-04-03 15:03

import filehive_auth.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filehive_auth', '0002_alter_user_managers_remove_user_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profilePicture',
            field=models.ImageField(blank=True, upload_to=filehive_auth.utils.user_directory_path),
        ),
    ]
