# Generated by Django 5.0.3 on 2024-04-06 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filehive_auth', '0003_alter_user_profilepicture'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelTable(
            name='user',
            table='Users',
        ),
    ]
